---
title: "Lombardy vs WA Plots"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, message=FALSE, warning=FALSE}
library(CoV19)
```

```{r italy_plot, message=FALSE, warning=FALSE}
my_plot(italy, "Lombardia", "2020-03-10")
```

```{r wa_plot, message=FALSE, warning=FALSE}
x <- subset(states, region=="WA")
tmp <- x[1,]
tmp$date <- as.Date("2020-03-26")
tmp[1,!colnames(tmp) %in% c("date", "region")] <- NA
tmp$positive <- 2580; tmp$death <- 132
x <- rbind(x, tmp)
reg <- "WA"
p <- my_plot(x, reg)
ymax <- max(subset(x, region==reg)$positive, na.rm=TRUE)
lockdown <- "2020-03-16"
ltext <- "restaurants close"
p <- p + geom_vline(xintercept = as.Date(lockdown)) +
    annotate("text", x=as.Date(lockdown)+0.5, y=.5*ymax, hjust=0, label=ltext, color="red", size=3, angle=90)
p <- p + geom_vline(xintercept = as.Date(lockdown)+12, linetype = "dashed") +
    annotate("text", x=as.Date(lockdown)+12+0.5, y=.5*ymax, hjust=0, label="12 days past restaurants closed", color="red", size=3, angle=90)
lockdown <- "2020-03-23"
ltext <- "stay at home order"
p <- p + geom_vline(xintercept = as.Date(lockdown)) +
    annotate("text", x=as.Date(lockdown)+0.5, y=.5*ymax, hjust=0, label=ltext, color="red", size=3, angle=90)
p
```

```{r world_plot, message=FALSE, warning=FALSE}
x <- world
x[x$date=="2020-02-12","positive"]=NA
x[x$date=="2020-02-13","positive"]=NA
p <- my_plot(x, "Hubei China", "2020-01-23")
p
```



